apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: secret-consumer-service
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  # roleArn: arn:aws:iam::608500418044:role/example-eks-service-account-secrets-role
  data:
    - key: secret-consumer-service/credentials
      name: password
      property: password
    - key: secret-consumer-service/credentials
      name: username
      property: username
