apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  serviceAccountName: cwl-fargate
  containers:
  - name: count
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      i=0;
      while true;
      do
        echo "$i: $(date) this is an app log" 2>&1 | tee -a /var/log/app.log;
        echo "$(date) $(uname -r) $i" 2>&1 | tee -a /var/log/system.log;
        i=$((i+1));
        sleep 60;
      done
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: count-agent
    image: amazon/aws-for-fluent-bit:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 2020
    env:
    - name: FLUENTD_HOST
      value: "fluentd"
    - name: FLUENTD_PORT
      value: "24224"
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: fluentbit-config
      mountPath: /fluent-bit/etc/
  terminationGracePeriodSeconds: 10
  volumes:
  - name: varlog
    emptyDir: {}
  - name: fluentbit-config
    configMap:
      name: fluentbit-config
