apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksfarg
  region: eu-west-1

managedNodeGroups:
  - name: ng-1-monitoring
    labels: { role: monitoring }
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
